function data = importData(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [INDEX,TIME,XAXIS,YAXIS,ZAXIS] = IMPORTFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   [INDEX,TIME,XAXIS,YAXIS,ZAXIS] = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [index,time,xAxis,yAxis,zAxis] = importfile('C1 test walking loose
%   _20150305_2118_left.csv',2, 3041);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/03/07 08:34:44

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    %%
    % 
    %   for x = 1:10
    %       disp(x)
    %   end
    % 
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);



%% Allocate imported array to column variable names
data.index = dataArray{:, 1};
data.time = dataArray{:, 2};
data.accel = [dataArray{:,3:5}];


